name: Continuous Integration

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: | 
        npm install -f opinion-app/package.json package --file opinion-app\package.json
        npm run build -f opinion-app/package.json package --file opinion-app\package.json --if-present
